---
- name: Update and upgrade Ubuntu system
  hosts: all
  become: yes
  tasks:

    - name: Update APT repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install security updates
      apt:
        upgrade: dist  # Opdatering af kun distribueringsopdateringer

    - name: Perform full system upgrade
      apt:
        upgrade: full  # Brug "full" i stedet for "upgrade" for en fuld opgradering

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean APT cache
      apt:
        autoclean: yes
