---
- name: Saml diskplads på server
  hosts: all
  gather_facts: false
  tasks:
    - name: Check disk space
      ansible.builtin.shell: df -h
      register: disk_usage

    - name: Print disk space
      ansible.builtin.debug:
        var: disk_usage.stdout

    - name: Gem disk space til en fil
      ansible.builtin.copy:
        content: "{{ disk_usage.stdout }}"
        dest: "/tmp/disk_usage_{{ inventory_hostname }}.log"
