---
- name: Tjek for bannede IP-adresser i Fail2ban
  hosts: all
  become: yes
  tasks:
    - name: Tjek bannede IP'er i sshd jail
      shell: fail2ban-client status sshd 2>/dev/null | grep "Banned IP list" || echo "No IPs banned"
      register: banned_ips
      changed_when: false

    - name: Vis bannede IP'er eller håndter tomt output
      debug:
        msg: >
          {% if banned_ips.stdout | trim == "No IPs banned" or not banned_ips.stdout %}
          Ingen IP'er er blevet bannet.
          {% else %}
          Bannede IP'er: {{ banned_ips.stdout.split(': ')[1] | default("Ingen IP'er fundet") }}
          {% endif %}
