---
- name: Fetch Ubuntu version from host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Show distribution name
      debug:
        msg: "Distribution: {{ ansible_facts['distribution'] }}"

    - name: Show distribution version
      debug:
        msg: "Version: {{ ansible_facts['distribution_version'] }}"

    - name: Show distribution codename
      debug:
        msg: "Codename: {{ ansible_facts['distribution_codename'] }}"

    - name: Show OS family
      debug:
        msg: "OS Family: {{ ansible_facts['os_family'] }}"