---
- name: Fetch Ubuntu version from host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Ubuntu version
      debug:
        msg: "The Ubuntu version on the host is {{ ansible_facts['distribution_version'] }}"
