---
- name: Fetch Ubuntu version from host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Show distribution name
      debug:
        msg: "Distribution: {{ ansible_facts['distribution'] }} Version: {{ ansible_facts['distribution_version'] }}"