---
- name: Fetch Ubuntu version from host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Ubuntu version
      debug:
        msg: "Denne server køre OS: {{ ansible_facts['distribution'] }}"
        msg: "Denne server køre Vesion: {{ ansible_facts['distribution_version'] }}"
