---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Run ping command
      shell: ping -c 10 -w 10 8.8.8.8
      register: ping_result
      ignore_errors: true

    - name: Show ping output
      debug:
        msg: "{{ ping_result.stdout }}"

    - name: Send status to Discord Webhook
      uri:
        url: "https://discord.com/api/webhooks/1339330700880646225/oWGXJi59Wfdq0hM9ZzNUnDM0JuAfedK-7JtDwFbfhLMo_iEoCxwinJ-yeNePbtXLrWcQ"
        method: POST
        body: "{{ lookup('template', 'discord_message.json.j2') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
      when: ping_result is defined
