---
- name: Ensure qemu-guest-agent is installed on Ubuntu VM
  hosts: all
  become: yes
  tasks:
    - name: Gather dpkg facts
      ansible.builtin.dpkg_facts:

    - name: Install qemu-guest-agent if not present
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      when: "'qemu-guest-agent' not in ansible_facts.packages"
      update_cache: yes
