---
- name: Ensure QEMU Guest Agent is installed and running
  hosts: all
  become: yes  # Brug sudo for at få adgang til systemadministrationskommandoer
  tasks:
    - name: Ensure qemu-guest-agent package is installed
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes  # Opdater pakkelisten, hvis nødvendigt
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure qemu-guest-agent service is enabled and running
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'