---
- name: Check and install QEMU guest agent on Ubuntu
  hosts: your_server_group
  become: yes
  tasks:
    - name: Ensure QEMU guest agent is installed
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes

    - name: Ensure the qemu-guest-agent service is enabled and running
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: yes
