---
- name: Kontroller og installer QEMU-agent på Ubuntu
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Kontroller om qemu-guest-agent er installeret
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present
      register: qemu_agent_status

    - name: Start og aktiver qemu-guest-agent service
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
      when: qemu_agent_status.changed
