---
- name: Ensure qemu-guest-agent is installed on Ubuntu VM
  hosts: all
  become: yes
  tasks:
    - name: Check if qemu-guest-agent is installed
      ansible.builtin.command: dpkg -l | grep qemu-guest-agent
      register: qemu_agent_check
      ignore_errors: yes

    - name: Install qemu-guest-agent if not present
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      when: qemu_agent_check.rc != 0
      update_cache: yes
