---
- name: Add ssh key
  hosts: Ubuntu
  become: true

  tasks:
  - name: Change sudoers file
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: 'bssa ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s