---
- name: Check Zabbix Agent Version
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Zabbix Agent version
      command: "zabbix_agentd -V"
      register: zabbix_version_output
      ignore_errors: true

    - name: Extract version
      set_fact:
        zabbix_version: "{{ zabbix_version_output.stdout_lines[0] | regex_search('Zabbix\s+(\d+\.\d+\.\d+)', '\1') }}"
      when: zabbix_version_output.rc == 0

    - name: Display Zabbix Agent version
      debug:
        msg: "Installed Zabbix Agent version: {{ zabbix_version | default('Not Installed') }}"